theme = "gruvbox_dark_hard"

[editor]
auto-save = true
auto-format = true
bufferline = "multiple"
color-modes = true
completion-replace = true
cursorcolumn = false
cursorline = true
line-number = "relative"
mouse = false
rulers = [79]
true-color = true

[editor.whitespace.render]
space = "none"
nbsp = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "╎"
skip-levels = 0

[editor.soft-wrap]
enable = true
max-wrap = 10 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40

[keys.normal]
del = "delete_selection"

[keys.insert]
del = "delete_char_forward"


